field isin
KCL-BMEIS/zoe-data-prep pull request #234
Opened 2021-12-06 15:07 UTC by Liyuan-Chen-1024

fix #226

2022-02-07 15:38 UTC, atbenmurray commented
IsIn algorithm framework:
1. sort the second sequence
2. for each element in the first sequence, do a binary search into the sorted secondary sequence
  a. optionally, find the unique values out of the sorted sequence and perform the binary search into the sorted, unique items

2022-02-08 11:46 UTC, Liyuan-Chen-1024 commented
np.array_equal() has almost same implementation as the self defined compare_arrays()

2022-02-09 08:51 UTC, deng113jie commented on exetera/core/fields.py
> +    return np.isin(field.data[:], test_elements)
Should this one also call FieldDataOps.apply_isin?

2022-02-18 14:30 UTC, atbenmurray requested changes

2022-02-18 18:57 UTC, atbenmurray approved these changes

2022-02-18 18:57 UTC, merged